// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExampleEvent demonstrates a simple event structure
// Replace this with your actual event schema
type ExampleEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique event identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The type of event (e.g., "transfer", "mint", "burn")
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Source account or contract
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Event-specific data as JSON string
	// In production, use structured fields instead
	Data string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// Event metadata
	Meta          *EventMeta `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleEvent) Reset() {
	*x = ExampleEvent{}
	mi := &file_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleEvent) ProtoMessage() {}

func (x *ExampleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleEvent.ProtoReflect.Descriptor instead.
func (*ExampleEvent) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExampleEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ExampleEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExampleEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ExampleEvent) GetMeta() *EventMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// EventMeta contains common metadata for all events
type EventMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ledger sequence number
	LedgerSequence uint32 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	// Transaction hash (hex string)
	TxHash string `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Operation index within the transaction
	OperationIndex uint32 `protobuf:"varint,3,opt,name=operation_index,json=operationIndex,proto3" json:"operation_index,omitempty"`
	// Ledger close time (Unix timestamp)
	LedgerCloseTime int64 `protobuf:"varint,4,opt,name=ledger_close_time,json=ledgerCloseTime,proto3" json:"ledger_close_time,omitempty"`
	// Whether the transaction was successful
	Successful    bool `protobuf:"varint,5,opt,name=successful,proto3" json:"successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventMeta) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *EventMeta) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *EventMeta) GetOperationIndex() uint32 {
	if x != nil {
		return x.OperationIndex
	}
	return 0
}

func (x *EventMeta) GetLedgerCloseTime() int64 {
	if x != nil {
		return x.LedgerCloseTime
	}
	return 0
}

func (x *EventMeta) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

// ExampleEventBatch is used for flowctl mode (batch output)
type ExampleEventBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All events extracted from a ledger
	Events []*ExampleEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Ledger sequence this batch was extracted from
	LedgerSequence uint32 `protobuf:"varint,2,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	// Total event count
	EventCount    uint32 `protobuf:"varint,3,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleEventBatch) Reset() {
	*x = ExampleEventBatch{}
	mi := &file_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleEventBatch) ProtoMessage() {}

func (x *ExampleEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleEventBatch.ProtoReflect.Descriptor instead.
func (*ExampleEventBatch) Descriptor() ([]byte, []int) {
	return file_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *ExampleEventBatch) GetEvents() []*ExampleEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ExampleEventBatch) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *ExampleEventBatch) GetEventCount() uint32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

var File_proto_events_proto protoreflect.FileDescriptor

const file_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x12proto/events.proto\x12\vdualmode.v1\"\x95\x01\n" +
	"\fExampleEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12*\n" +
	"\x04meta\x18\x05 \x01(\v2\x16.dualmode.v1.EventMetaR\x04meta\"\xc2\x01\n" +
	"\tEventMeta\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12'\n" +
	"\x0foperation_index\x18\x03 \x01(\rR\x0eoperationIndex\x12*\n" +
	"\x11ledger_close_time\x18\x04 \x01(\x03R\x0fledgerCloseTime\x12\x1e\n" +
	"\n" +
	"successful\x18\x05 \x01(\bR\n" +
	"successful\"\x90\x01\n" +
	"\x11ExampleEventBatch\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.dualmode.v1.ExampleEventR\x06events\x12'\n" +
	"\x0fledger_sequence\x18\x02 \x01(\rR\x0eledgerSequence\x12\x1f\n" +
	"\vevent_count\x18\x03 \x01(\rR\n" +
	"eventCountBEZCgithub.com/withObsrvr/flowctl-sdk/examples/dual-mode-template/protob\x06proto3"

var (
	file_proto_events_proto_rawDescOnce sync.Once
	file_proto_events_proto_rawDescData []byte
)

func file_proto_events_proto_rawDescGZIP() []byte {
	file_proto_events_proto_rawDescOnce.Do(func() {
		file_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)))
	})
	return file_proto_events_proto_rawDescData
}

var file_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_events_proto_goTypes = []any{
	(*ExampleEvent)(nil),      // 0: dualmode.v1.ExampleEvent
	(*EventMeta)(nil),         // 1: dualmode.v1.EventMeta
	(*ExampleEventBatch)(nil), // 2: dualmode.v1.ExampleEventBatch
}
var file_proto_events_proto_depIdxs = []int32{
	1, // 0: dualmode.v1.ExampleEvent.meta:type_name -> dualmode.v1.EventMeta
	0, // 1: dualmode.v1.ExampleEventBatch.events:type_name -> dualmode.v1.ExampleEvent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_events_proto_init() }
func file_proto_events_proto_init() {
	if File_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_events_proto_rawDesc), len(file_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_events_proto_goTypes,
		DependencyIndexes: file_proto_events_proto_depIdxs,
		MessageInfos:      file_proto_events_proto_msgTypes,
	}.Build()
	File_proto_events_proto = out.File
	file_proto_events_proto_goTypes = nil
	file_proto_events_proto_depIdxs = nil
}
